[package]
name = "skid_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.5.0", features = ["default", "cuda"] } # Cubecl 라이브러리 의존성
bytemuck = "1"

[lib]
name = "skid_rust_backend" # 라이브러리 파일 이름에 영향을 줍니다.
crate-type = ["cdylib"]
